import Image from "next/image";
import React from "react";
import { useSelector } from "react-redux";
import CheckoutProduct from "../components/CheckoutProduct";
import Header from "../components/Header";
import { selectItems, selectTotal } from "../slices/basketSlice";
import Currency from "react-currency-formatter";
import { useSession } from "next-auth/react";
import Head from "next/head";

type CheckoutProps = {};

const Checkout: React.FC<CheckoutProps> = () => {
  const items = useSelector(selectItems);
  const { data: session } = useSession();
  const total = useSelector(selectTotal);

  return (
    <div className="bg-gray-100">
      <Head>
        <title>Checkout</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="lg:flex mx-auto max-w-screen-2xl">
        <div className="flex-grow m-5 shadow-sm ">
          <Image
            src="https://links.papareact.com/ikj"
            width={1020}
            height={250}
            objectFit="contain"
          />

          <div className="flex flex-col p-5 space-y-10 bg-white">
            <h1 className="text-3xl border-b pb-4">
              {items.length === 0
                ? "Your Amazon Basket is Empty"
                : `Shoping Basket`}
            </h1>
            {items.map((item, i) => (
              <CheckoutProduct
                id={item.id}
                key={i}
                title={item.title}
                price={item.price}
                image={item.image}
                description={item.description}
                category={item.category}
                prime={item.prime}
                rating={item.rating}
              />
            ))}
          </div>
        </div>
        <div>
          <div className="flex flex-col bg-white p-10 shadow-md">
            {items.length > 0 && (
              <div className="flex flex-col bg-white mx-8 my-5 p-5">
                <>
                  <h2 className="whitespace-nowrap">
                    Subtotal: ({items.length} items):
                    <span className="font-bold">
                      <Currency quantity={total} currency="USD" />
                    </span>
                  </h2>
                  <button
                    role="link"
                    disabled={!session}
                    className={`button mt-2 ${
                      !session &&
                      "from-gray-300 to-gray-500 border-gray-200 text-gray-300 cursor-not-allowed"
                    }`}
                  >
                    {!session ? "Sign in to check out" : "Proceed to check out"}
                  </button>
                </>
              </div>
            )}
          </div>
        </div>
      </main>
    </div>
  );
};
export default Checkout;
